# Generated by Django 2.1.2 on 2018-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenedata',
            name='scene',
        ),
        migrations.AddField(
            model_name='scene',
            name='file_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='scene',
            name='html_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SceneData',
        ),
    ]
