# Generated by Django 2.1.2 on 2018-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20181028_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='html_text',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='scene',
            name='file_audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
