# Generated by Django 2.1.2 on 2018-10-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20181028_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
