# Generated by Django 2.1.2 on 2018-10-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='html_emded_code',
            new_name='html_embed_code',
        ),
    ]
